### PR TITLE
Add support for proxies and other requests parameters

### PR DESCRIPTION
**Pull request by goranfr**
HTTP / HTTPS proxies to use can be specified via config file
or when creating a Session. Other arguments recognized by requests can be
passed when creating a Session as well, and will be used with every request.

### CODE REVIEW

**Comment by goranfr** [comment]
The code as-is will *not* use environment variables `HTTP_PROXY` and `HTTPS_PROXY`, as using prepared requests and `send` explicitly avoids that. We could just add a `session.merge_environment_settings()` and call it a day though.

**Comment by haraldnh** [comment]
I would think the best solution would be to drop `prepare_request` completely from our `session.data_request`, and just call `res = self._session.request(...)` to do everything?  That should both fix this and move us closer to the way the docs say we should be using the library?

**Comment by haraldnh** [comment]
@goranfr Can you review and merge if you agree?

**Comment by goranfr** [comment]
Looks good to me.

**Pull request merged**
